// Consumer smoke test — the one place in this repo that resolves the packages the way npm does.
//
// Every other path that says `@oriui/vue` or `@oriui/headless` (vitest, the docs, the e2e harness,
// the library build) is ALIASED to `src/`, so `dist/` and the `exports` maps were built, weighed by
// size-limit and statically parsed by publint/attw — but never executed. See ISSUES-INNER ORI-I-30.
//
// What this does: `npm pack` the three workspaces, install the tarballs plus vue/svelte/react into a
// throwaway directory, and run one ESM module there that imports every published entry point through
// its `exports` map and asserts a real export from each.
//
// Packing runs each package's `prepack` (= its build) unless ORI_SMOKE_IGNORE_SCRIPTS=1 is set, so a
// missing or stale `dist` cannot pass. In CI the build step has already run, so that variable is set
// there to pack the exact artifact the rest of the gate measured and keep the job short.
// ORI_SMOKE_KEEP=1 leaves the scratch directory in place for inspection.
import { spawnSync } from 'node:child_process'
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const PACKAGES = ['@oriui/css', '@oriui/headless', '@oriui/vue']

// The module that runs inside the consumer install. Kept as a string so the smoke test stays one
// file; nothing in it may reference this module's scope.
const ASSERTIONS = `// Generated by scripts/smoke-pack.mjs — runs inside the throwaway consumer install.
import { createRequire } from 'node:module'
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'

const require = createRequire(import.meta.url)
const failures = []

function check(label, fn) {
    try {
        fn()
        console.log('  ok   ' + label)
    } catch (error) {
        failures.push(label)
        console.log('  FAIL ' + label + ' -- ' + error.message)
    }
}

function assert(condition, message) {
    if (!condition) throw new Error(message)
}

// --- the styled Vue layer: resolved through its exports map, executed, real components returned ---
const vue = await import('@oriui/vue')
check('@oriui/vue exports OriButton as a component', () => {
    const OriButton = vue.OriButton
    assert(OriButton, 'OriButton is missing from the barrel')
    assert(typeof OriButton === 'object' || typeof OriButton === 'function', 'OriButton is not a component')
    assert(typeof OriButton.render === 'function' || typeof OriButton.setup === 'function', 'OriButton has no render/setup')
})
check('@oriui/vue ships the whole catalog', () => {
    const components = Object.keys(vue).filter((k) => k.startsWith('Ori'))
    assert(components.length >= 34, 'only ' + components.length + ' Ori* exports resolved')
})

// --- the headless engine + its three adapters, each through its own subpath export ---
const core = await import('@oriui/headless')
check('@oriui/headless (core) exports applyTheme + createMachine', () => {
    assert(typeof core.applyTheme === 'function', 'applyTheme is not a function')
    assert(typeof core.createMachine === 'function', 'createMachine is not a function')
})

for (const adapter of ['vue', 'svelte', 'react']) {
    const mod = await import('@oriui/headless/' + adapter)
    check('@oriui/headless/' + adapter + ' exports useDialog + useTabs + normalizeProps', () => {
        assert(typeof mod.useDialog === 'function', 'useDialog is not a function')
        assert(typeof mod.useTabs === 'function', 'useTabs is not a function')
        assert(mod.normalizeProps, 'normalizeProps is missing')
    })
}

// --- the CSS layer: no JS to import, so resolve every documented entry through the exports map ---
const cssEntries = [
    '@oriui/css',
    '@oriui/css/styles.css',
    '@oriui/css/base.css',
    '@oriui/css/tokens.css',
    '@oriui/css/reset.css',
    '@oriui/css/components/button.css'
]
for (const entry of cssEntries) {
    check(entry + ' resolves to a real stylesheet', () => {
        const file = require.resolve(entry)
        assert(existsSync(file), 'resolved to a missing file: ' + file)
        assert(readFileSync(file, 'utf8').includes('@layer'), 'resolved file carries no @layer -- not an oriUI stylesheet')
    })
}
check('@oriui/css/components/button.css carries the button block', () => {
    const css = readFileSync(require.resolve('@oriui/css/components/button.css'), 'utf8')
    assert(css.includes('.ori-button'), 'no .ori-button rule in the a-la-carte component file')
})

// --- what npm actually put in the tarball (the manifest-level claim, now measured) ---
for (const name of ['@oriui/vue', '@oriui/headless', '@oriui/css']) {
    check(name + ' ships LICENSE + CHANGELOG.md in the tarball', () => {
        const dir = dirname(require.resolve(name + '/package.json'))
        assert(existsSync(join(dir, 'LICENSE')), 'no LICENSE in the installed package')
        assert(existsSync(join(dir, 'CHANGELOG.md')), 'no CHANGELOG.md in the installed package')
    })
}

// --- adapter isolation: the premise the optional peers rest on (ISSUES-INNER ORI-I-38) ---
// Each subpath entry may only reach its OWN framework, transitively through the shared chunks. If
// dist/vue/index.js could pull in react, marking all three peers optional would be unsound.
function bareImports(entry) {
    const seen = new Set()
    const bare = new Set()
    const queue = [entry]
    while (queue.length) {
        const file = queue.pop()
        if (seen.has(file) || !existsSync(file)) continue
        seen.add(file)
        for (const match of readFileSync(file, 'utf8').matchAll(/(?:\\bfrom\\s*|\\bimport\\s*\\(\\s*)(['"])([^'"]+)\\1/g)) {
            const spec = match[2]
            if (spec.startsWith('.')) queue.push(resolve(dirname(file), spec))
            else bare.add(spec.split('/')[0])
        }
    }
    return bare
}

const headlessDir = dirname(require.resolve('@oriui/headless/package.json'))
const FRAMEWORKS = ['vue', 'svelte', 'react']
check('@oriui/headless core reaches no framework at all', () => {
    const reached = [...bareImports(join(headlessDir, 'dist', 'core', 'index.js'))].filter((s) => FRAMEWORKS.includes(s))
    assert(reached.length === 0, 'core imports ' + reached.join(', '))
})
for (const adapter of FRAMEWORKS) {
    check('@oriui/headless/' + adapter + ' reaches only ' + adapter, () => {
        const reached = [...bareImports(join(headlessDir, 'dist', adapter, 'index.js'))].filter((s) => FRAMEWORKS.includes(s))
        assert(reached.length > 0, 'the ' + adapter + ' entry imports no framework at all -- did the entry resolve?')
        const foreign = reached.filter((s) => s !== adapter)
        assert(foreign.length === 0, 'the ' + adapter + ' entry also imports ' + foreign.join(', '))
    })
}

// --- the one thing a duplicate install would break silently (ISSUES-INNER ORI-I-42) ---
check('@oriui/headless resolves to a single copy from both consumers', () => {
    const fromRoot = require.resolve('@oriui/headless/package.json')
    const fromVue = createRequire(require.resolve('@oriui/vue/package.json')).resolve('@oriui/headless/package.json')
    assert(fromRoot === fromVue, 'two copies installed: ' + fromRoot + ' and ' + fromVue)
})
check('@oriui/vue nests no sibling copy', () => {
    const nested = join(dirname(require.resolve('@oriui/vue/package.json')), 'node_modules')
    const inside = existsSync(nested) ? readdirSync(nested) : []
    assert(!inside.includes('@oriui'), '@oriui/vue nested its own copy of a sibling')
})

if (failures.length) {
    console.error('smoke: ' + failures.length + ' check(s) failed')
    process.exit(1)
}
`

function run(cmd, args, cwd) {
    const result = spawnSync(cmd, args, { cwd, stdio: 'inherit' })
    if (result.status !== 0) {
        throw new Error(`smoke: \`${cmd} ${args.join(' ')}\` exited with ${result.status ?? result.signal}`)
    }
}

// Run npm through its own cli.js under the current node rather than the `npm`/`npm.cmd` shim: Node
// refuses to spawn a `.cmd` without `shell: true`, and a shell would need every path re-quoted
// (`process.execPath` is `C:\Program Files\nodejs\node.exe` on Windows) and warns DEP0190. npm sets
// `npm_execpath` for its own run-scripts, which is how this is always invoked.
const NPM_CLI = process.env.npm_execpath
function npm(args, cwd) {
    if (!NPM_CLI?.endsWith('.js')) throw new Error('smoke: no npm_execpath — run this as `npm run smoke`')
    run(process.execPath, [NPM_CLI, ...args], cwd)
}

const started = Date.now()
const scratch = mkdtempSync(join(tmpdir(), 'oriui-smoke-'))
const consumer = join(scratch, 'consumer')

try {
    // 1. Pack the three workspaces exactly as `npm publish` would.
    const packArgs = ['pack', ...PACKAGES.flatMap((name) => ['-w', name]), '--pack-destination', scratch]
    packArgs.push('--loglevel=error') // the per-file `npm notice` listing is 400 lines of noise here
    if (process.env.ORI_SMOKE_IGNORE_SCRIPTS === '1') packArgs.push('--ignore-scripts')
    npm(packArgs, ROOT)

    const tarballs = readdirSync(scratch)
        .filter((f) => f.endsWith('.tgz'))
        .map((f) => join(scratch, f))
    if (tarballs.length !== PACKAGES.length) {
        throw new Error(`smoke: expected ${PACKAGES.length} tarballs, got ${tarballs.length}`)
    }

    // 2. A throwaway consumer that has never heard of this repo's aliases.
    mkdirSync(consumer, { recursive: true })
    const manifest = { name: 'oriui-smoke-consumer', private: true, version: '0.0.0', type: 'module' }
    writeFileSync(join(consumer, 'package.json'), `${JSON.stringify(manifest, null, 2)}\n`)

    // vue/svelte/react are the three optional peers of @oriui/headless; all three are installed so
    // every adapter entry can actually be imported. --prefer-offline keeps this on the npm cache.
    const installArgs = ['install', ...tarballs, 'vue@^3.5', 'svelte@^5', 'react@^19']
    npm([...installArgs, '--no-audit', '--no-fund', '--prefer-offline', '--loglevel=error'], consumer)

    // 3. Execute the installed artifacts.
    writeFileSync(join(consumer, 'smoke.mjs'), ASSERTIONS)
    run(process.execPath, ['smoke.mjs'], consumer)

    console.log(
        `smoke: every published entry point imports and resolves (${((Date.now() - started) / 1000).toFixed(1)}s)`
    )
} finally {
    if (process.env.ORI_SMOKE_KEEP === '1') console.log(`smoke: scratch kept at ${scratch}`)
    else rmSync(scratch, { recursive: true, force: true })
}
